### ISSUE TITLE
StartupEvents does not work.

### ISSUE THREAD

**Issue by Sorinstratu** [KubeJS-Mods/KubeJS-Mekanism#10]
[EXAMPLE]:

StartupEvents.registry("mekanism.infuse_type", event =>{
event.create("nickel").color(10195319).displayName("Nickel");
})

[ERROR]:

! [18:48:38] [ERR] startup_scripts:mekanism_registory.js:1: Event handler 'StartupEvents.registry' doesn't accept id 'minecraft:mekanism.infuse_type'!

**Comment by MaxNeedsSnacks** [comment]
Use a colon, not a period (mekanism:infuse_type)

**Comment by Sorinstratu** [comment]
! [16:07:26] [ERR] startup_scripts:mekanism_registory.js:1: Event handler 'StartupEvents.registry' doesn't accept id 'mekanism:infuse_type'!
