### ISSUE TITLE
Crushing, Enriching not working

### ISSUE THREAD

**Issue by HakeemAzma** [KubeJS-Mods/KubeJS-Mekanism#11]
Both the KubeJS Mekanism and event.custom not working for crushing and enriching.

**Comment by dctime** [comment]
Try to remove the kubejs mekanism mod and try event.custom. Weird stuff.

**Comment by dctime** [comment]
> Both the KubeJS Mekanism and event.custom not working for crushing and enriching.

Try remove the kubejs mekanism mod and try event.custom. Weird stuff.
