### ISSUE TITLE
Metallurgic Infusion Syntax Error

### ISSUE THREAD

**Issue by naviqube** [KubeJS-Mods/KubeJS-Mekanism#7]
Minecraft 1.18.2
KubeJS Mekanism 1802.1.3-build.6
Mekanism 1.18.2-10.2.0.459

event.recipes.mekanismMetallurgicInfusing(output, inputItem, infusionInput, infusionAmount)
Currently throws the following error: com.google.gson.JsonSyntaxException: Missing chemicalInput, expected to find a JsonObject

Looking into the code of Mekanism, it appears they replaced infusionInput with chemicalInput, causing KubeJS recipes to break.

**Comment by MaxNeedsSnacks** [comment]
Should hopefully be fixed in the new release ^
^

**Comment by MaxNeedsSnacks** [comment]
Looks like the merge failed, give me just a second

**Comment by naviqube** [comment]
Thank you for the lightning quick fix! That said, the update is requiring KubeJS build 407 as a dependency, while the newest published version I can find is build 405. I was able to change the dependency in the TOML file to work around it and the recipes work flawlessly - but that's probably not something I should be doing willy nilly.

**Comment by MaxNeedsSnacks** [comment]
Oops yeah, some changes were left pending a release because I wanted to add something new as well, the new release **should** be out now ^^

**Comment by naviqube** [comment]
Can confirm it works perfectly. Thank you so much for your responsiveness!
